<?php
/**
 * InstallmentResultModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PayIn3\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Capayable API V2
 *
 * API for Pay after delivery and Pay in 3 installments
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PayIn3\Client;

/**
 * InstallmentResultModelTest Class Doc Comment
 *
 * @category    Class
 * @description InstallmentResultModel
 * @package     PayIn3\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InstallmentResultModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InstallmentResultModel"
     */
    public function testInstallmentResultModel()
    {
    }

    /**
     * Test attribute "is_accepted"
     */
    public function testPropertyIsAccepted()
    {
    }
}
