<?php
/**
 * InstallmentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PayIn3\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Capayable API V2
 *
 * API for Pay after delivery and Pay in 3 installments
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace PayIn3\Client;

use \PayIn3\Client\Configuration;
use \PayIn3\Client\ApiException;
use \PayIn3\Client\ObjectSerializer;

/**
 * InstallmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  PayIn3\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstallmentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for installmentV2Post
     *
     * # Register first installment payment (own PSP only)    For ‘in three installments’ orders, register the first installment payment immediately after the creditcheck. Only use this if you don’t pay through Capayable but use your own PSP (option B above)..
     *
     */
    public function testInstallmentV2Post()
    {
    }
}
